server:
  port: 9999

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springboot_demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        format_sql: false
  freemarker:
    suffix: .html
  application:
    name: spring-boot-demo
#  redis:
#      host: codis.fenqi.test.d.xiaonei.com
#      port: 6379

wechat:
  config:
    apps:
      - appCode: SAAS_WECHAT
        appId: wx6080c31355b4073e
        appSecret: 5224a224c6912d26c0b6ade3247e8440

system:
  corePoolSize: 40
  maxPoolSize: 80
  queueCapacity: 80
  redisKey: wx